"""
Unit tests for finalg.cayley_table: CayleyTable, make_cayley_table,
index_table_from_name_table, and about_tables.

@author: Alfred J. Reich
"""

import io
import contextlib
from unittest import TestCase

from finalg.cayley_table import (
    CayleyTable,
    make_cayley_table,
    index_table_from_name_table,
    about_tables,
)


class TestCayleyTableConstruction(TestCase):

    def test_valid_square_table(self):
        tbl = CayleyTable([[0, 1], [1, 0]])
        self.assertEqual(tbl.order, 2)

    def test_non_square_table_raises(self):
        with self.assertRaises(Exception):
            CayleyTable([[0, 1, 2], [1, 0, 2]])

    def test_out_of_range_high_raises(self):
        with self.assertRaises(Exception):
            CayleyTable([[0, 1], [1, 2]])

    def test_out_of_range_negative_raises(self):
        with self.assertRaises(Exception):
            CayleyTable([[0, 1], [1, -1]])


class TestCayleyTable(TestCase):

    def setUp(self) -> None:
        # not assoc; is comm; no identity -- the RPS magma table, above
        self.tbl1 = [[0, 1, 0],
                     [1, 1, 2],
                     [0, 2, 2]]
        self.tbl1_copy = [[0, 1, 0],
                          [1, 1, 2],
                          [0, 2, 2]]

        # is assoc; not comm; has identity (0) --- the S3 group table
        self.tbl2 = [[0, 1, 2, 3, 4, 5],
                     [1, 2, 0, 5, 3, 4],
                     [2, 0, 1, 4, 5, 3],
                     [3, 4, 5, 0, 1, 2],
                     [4, 5, 3, 2, 0, 1],
                     [5, 3, 4, 1, 2, 0]]

        # is assoc; is comm; has identity (0) --- the Z4 group table
        self.tbl3 = [[0, 1, 2, 3],
                     [1, 2, 3, 0],
                     [2, 3, 0, 1],
                     [3, 0, 1, 2]]

        # powerset(3) group table
        self.tbl4 = [[0, 1, 2, 3, 4, 5, 6, 7],
                     [1, 0, 4, 5, 2, 3, 7, 6],
                     [2, 4, 0, 6, 1, 7, 3, 5],
                     [3, 5, 6, 0, 7, 1, 2, 4],
                     [4, 2, 1, 7, 0, 6, 5, 3],
                     [5, 3, 7, 1, 6, 0, 4, 2],
                     [6, 7, 3, 2, 5, 4, 0, 1],
                     [7, 6, 5, 4, 3, 2, 1, 0]]

        # Example 1.4.1 in "Groupoids and Smarandache Groupoids", W. B. Vasantha Kandasamy
        self.tbl5 = [[0, 3, 0, 3, 0, 3],
                     [1, 4, 1, 4, 1, 4],
                     [2, 5, 2, 5, 2, 5],
                     [3, 0, 3, 0, 3, 0],
                     [4, 1, 4, 1, 4, 1],
                     [5, 2, 5, 2, 5, 2]]

        # TABLES FOR RINGS & FIELDS:

        # Addition table of the Ring on the powerset of {0, 1}
        self.tbl6a = [[0, 1, 2, 3],
                      [1, 0, 3, 2],
                      [2, 3, 0, 1],
                      [3, 2, 1, 0]]

        # Multiplication table of the Ring on the powerset of {0, 1}
        self.tbl6m = [[0, 0, 0, 0],
                      [0, 1, 0, 1],
                      [0, 0, 2, 2],
                      [0, 1, 2, 3]]

        # Addition table for the Ring based on 2x2 matrices
        self.tbl7a = [[0, 1, 2, 3],
                      [1, 0, 3, 2],
                      [2, 3, 0, 1],
                      [3, 2, 1, 0]]

        # Multiplication table for the Ring based on 2x2 matrices
        self.tbl7m = [[0, 0, 0, 0],
                      [0, 0, 1, 1],
                      [0, 0, 2, 2],
                      [0, 0, 3, 3]]

        # Addition table of autogenerated Ring of integers mod 6
        self.tbl8a = [[0, 1, 2, 3, 4, 5],
                      [1, 2, 3, 4, 5, 0],
                      [2, 3, 4, 5, 0, 1],
                      [3, 4, 5, 0, 1, 2],
                      [4, 5, 0, 1, 2, 3],
                      [5, 0, 1, 2, 3, 4]]

        # Multiplication table of autogenerated Ring of integers mod 6
        self.tbl8m = [[0, 0, 0, 0, 0, 0],
                      [0, 1, 2, 3, 4, 5],
                      [0, 2, 4, 0, 2, 4],
                      [0, 3, 0, 3, 0, 3],
                      [0, 4, 2, 0, 4, 2],
                      [0, 5, 4, 3, 2, 1]]

        # Quasigroup
        self.tbl9 = [[0, 4, 8, 2, 3, 9, 6, 7, 1, 5],
                     [3, 6, 2, 8, 7, 1, 9, 5, 0, 4],
                     [8, 9, 3, 1, 0, 6, 4, 2, 5, 7],
                     [1, 7, 6, 5, 4, 8, 0, 3, 2, 9],
                     [2, 1, 9, 0, 6, 7, 5, 8, 4, 3],
                     [5, 2, 7, 4, 9, 3, 1, 0, 8, 6],
                     [4, 3, 0, 6, 1, 5, 2, 9, 7, 8],
                     [9, 8, 5, 7, 2, 0, 3, 4, 6, 1],
                     [7, 0, 1, 9, 5, 4, 8, 6, 3, 2],
                     [6, 5, 4, 3, 8, 2, 7, 1, 9, 0]]

        test_arrays = [self.tbl1, self.tbl2, self.tbl3, self.tbl4, self.tbl5, self.tbl9]

        test_arrays_add = [self.tbl6a, self.tbl7a, self.tbl8a]
        test_arrays_mult = [self.tbl6m, self.tbl7m, self.tbl8m]

        self.test_tables = [CayleyTable(tbl) for tbl in test_arrays]
        self.test_tables_add = [CayleyTable(tbl) for tbl in test_arrays_add]
        self.test_tables_mult = [CayleyTable(tbl) for tbl in test_arrays_mult]
        self.all_tables = self.test_tables + self.test_tables_add + self.test_tables_mult

    # ABOUT TEST_TABLES:
    #
    #    Table  Order  Associative?  Commutative?  Left Id?  Right Id? Cancel?  Identity?  Inverses?  Algebra?
    # ---------------------------------------------------------------------------------------------------------
    #      1      3       False         True         None      None     False       None      False      Magma
    #      2      6        True        False            0         0      True          0       True      Group
    #      3      4        True         True            0         0      True          0       True      Group
    #      4      8        True         True            0         0      True          0       True      Group
    #      5      6        True        False         None         0     False       None      False  Semigroup
    #      6     10       False        False         None      None      True       None      False Quasigroup
    # NOTE: Creating an inverse_lookup_dict requires that the index, "id", of the identity
    # element be provided.

    def test_inverse_lookup_dict_1(self):
        tb1 = self.test_tables[1]
        id1 = 0
        self.assertEqual(tb1.inverse_lookup_dict(id1), {0: 0, 1: 2, 2: 1, 3: 3, 4: 4, 5: 5})

    def test_inverse_lookup_dict_2(self):
        tb2 = self.test_tables[2]
        id2 = 0
        self.assertEqual(tb2.inverse_lookup_dict(id2), {0: 0, 1: 3, 2: 2, 3: 1})

    def test_inverse_lookup_dict_with_element_names(self):
        tb2 = self.test_tables[2]  # Z4
        result = tb2.inverse_lookup_dict(0, elements=('e', 'a', 'a2', 'a3'))
        self.assertEqual(result, {'e': 'e', 'a': 'a3', 'a2': 'a2', 'a3': 'a'})

    def test_table_order(self):
        result = [tbl.order for tbl in self.all_tables]
        self.assertEqual(result, [3, 6, 4, 8, 6, 10, 4, 4, 6, 4, 4, 6])

    def test_table_associative(self):
        result = [tbl.is_associative() for tbl in self.all_tables]
        self.assertEqual(result, [False, True, True, True, True, False, True, True, True, True, True, True])

    def test_table_commutative(self):
        result = [tbl.is_commutative() for tbl in self.all_tables]
        self.assertEqual(result, [True, False, True, True, False, False, True, True, True, True, False, True])

    def test_table_left_id(self):
        result = [tbl.left_identity() for tbl in self.test_tables]
        self.assertEqual(result, [None, 0, 0, 0, None, None])

    def test_table_right_id(self):
        result = [tbl.right_identity() for tbl in self.test_tables]
        self.assertEqual(result, [None, 0, 0, 0, 0, None])

    def test_table_identity(self):
        result = [tbl.identity() for tbl in self.test_tables]
        self.assertEqual(result, [None, 0, 0, 0, None, None])

    def test_table_has_inverses(self):
        result = [tbl.has_inverses() for tbl in self.test_tables]
        self.assertEqual(result, [False, True, True, True, False, False])

    def test_cayley_table_to_str(self):
        result = str(CayleyTable(self.tbl3))
        self.assertEqual(result[:26], '<CayleyTable, order 4, ID:')

    def test_cayley_table_to_list(self):
        result = CayleyTable(self.tbl3).tolist()
        self.assertEqual(result, [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]])

    def test_cayley_table_to_list_with_names(self):
        result = CayleyTable(self.tbl3).to_list_with_names(["e", "a", "a^2", "a^3"])
        answer = [['e', 'a', 'a^2', 'a^3'],
                  ['a', 'a^2', 'a^3', 'e'],
                  ['a^2', 'a^3', 'e', 'a'],
                  ['a^3', 'e', 'a', 'a^2']]
        self.assertEqual(result, answer)

    def test_equal(self):
        self.assertEqual(CayleyTable(self.tbl1), CayleyTable(self.tbl1_copy))

    def test_not_equal_different_tables(self):
        self.assertNotEqual(CayleyTable(self.tbl1), CayleyTable(self.tbl3))

    def test_equal_to_non_cayley_table_is_not_implemented(self):
        self.assertFalse(CayleyTable(self.tbl1) == [[0, 1, 0], [1, 1, 2], [0, 2, 2]])
        self.assertTrue(CayleyTable(self.tbl1) != "not a table")

    def test_hash_consistent_with_equality(self):
        # CayleyTable.__hash__ was fixed to hash a tuple-of-tuples (previously a
        # tuple-of-lists, which always raised TypeError). Equal tables now hash equal.
        self.assertEqual(hash(CayleyTable(self.tbl1)), hash(CayleyTable(self.tbl1_copy)))

    def test_hashable_in_a_set(self):
        s = {CayleyTable(self.tbl1), CayleyTable(self.tbl1_copy), CayleyTable(self.tbl3)}
        self.assertEqual(len(s), 2)

    def test_repr_roundtrips_via_eval(self):
        tbl = CayleyTable(self.tbl3)
        rebuilt = eval(repr(tbl))
        self.assertEqual(tbl, rebuilt)

    def test_getitem(self):
        tbl = CayleyTable(self.tbl3)
        self.assertEqual(tbl[1, 2], 3)
        self.assertEqual(tbl[0, 0], 0)

    def test_table_property_returns_ndarray(self):
        tbl = CayleyTable(self.tbl3)
        self.assertEqual(tbl.table.shape, (4, 4))
        self.assertEqual(tbl.table[2][1], 3)

    def test_mult_distributes_over_add(self):
        result = [m.distributes_over(a) for (m, a) in zip(self.test_tables_mult, self.test_tables_add)]
        self.assertEqual(result, [True, True, True])

    def test_add_distributes_over_mult(self):
        result = [a.distributes_over(m) for (m, a) in zip(self.test_tables_mult, self.test_tables_add)]
        self.assertEqual(result, [False, False, False])

    def test_distributes_over_verbose_smoke(self):
        # Just make sure the verbose branch runs without error and gives the same answer.
        m, a = self.test_tables_mult[0], self.test_tables_add[0]
        with contextlib.redirect_stdout(io.StringIO()):
            result = a.distributes_over(m, verbose=True)
        self.assertFalse(result)

    def test_has_cancellation_verbose_smoke(self):
        with contextlib.redirect_stdout(io.StringIO()):
            result = CayleyTable(self.tbl9).has_cancellation(verbose=True)
        self.assertTrue(result)

    def test_table_entries_where_equal_to(self):
        tbl = CayleyTable(self.tbl3)  # Z4
        pairs = tbl.table_entries_where_equal_to(0)
        pairs_as_ints = sorted((int(r), int(c)) for r, c in pairs)
        self.assertEqual(pairs_as_ints, [(0, 0), (1, 3), (2, 2), (3, 1)])

    def test_type_of_algebra_magma(self):
        self.assertEqual(CayleyTable(self.tbl1).type_of_algebra(), "Magma")

    def test_type_of_algebra_group(self):
        self.assertEqual(CayleyTable(self.tbl2).type_of_algebra(), "Group")
        self.assertEqual(CayleyTable(self.tbl3).type_of_algebra(), "Group")

    def test_type_of_algebra_semigroup(self):
        self.assertEqual(CayleyTable(self.tbl5).type_of_algebra(), "Semigroup")

    def test_type_of_algebra_quasigroup(self):
        self.assertEqual(CayleyTable(self.tbl9).type_of_algebra(), "Quasigroup")

    def test_type_of_algebra_monoid(self):
        # Commutative multiplication mod 4 has an identity ('1') but 0 & 2 lack inverses.
        monoid_tbl = CayleyTable([[(a * b) % 4 for b in range(4)] for a in range(4)])
        self.assertEqual(monoid_tbl.type_of_algebra(), "Monoid")

    def test_type_of_algebra_loop(self):
        loop_tbl = CayleyTable([[0, 1, 2, 3, 4, 5, 6],
                                 [1, 2, 0, 5, 6, 4, 3],
                                 [2, 0, 1, 6, 5, 3, 4],
                                 [3, 6, 5, 4, 0, 1, 2],
                                 [4, 5, 6, 0, 3, 2, 1],
                                 [5, 3, 4, 2, 1, 6, 0],
                                 [6, 4, 3, 1, 2, 0, 5]])
        self.assertEqual(loop_tbl.type_of_algebra(), "Loop")

    def test_about_printout_smoke(self):
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            result = CayleyTable(self.tbl3)._about(printout=True)
        self.assertIsNone(result)
        self.assertIn("Order", buf.getvalue())

    def test_about_no_printout_returns_tuple(self):
        result = CayleyTable(self.tbl1)._about(printout=False)
        self.assertEqual(len(result), 9)
        self.assertEqual(result[0], "3")  # order
        self.assertEqual(result[8], "Magma")  # algebra type

    def test_about_tables(self):
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            about_tables(self.test_tables)
        output = buf.getvalue()
        self.assertIn("Algebra?", output)
        self.assertIn("Group", output)


class TestMakeCayleyTable(TestCase):

    def test_from_index_table(self):
        elements = ('e', 'a', 'a2', 'a3')
        result = make_cayley_table([[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], elements)
        self.assertIsInstance(result, CayleyTable)
        self.assertEqual(result.tolist(), [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]])

    def test_from_name_table(self):
        elements = ('e', 'a', 'a2', 'a3')
        name_table = [['e', 'a', 'a2', 'a3'],
                      ['a', 'a2', 'a3', 'e'],
                      ['a2', 'a3', 'e', 'a'],
                      ['a3', 'e', 'a', 'a2']]
        result = make_cayley_table(name_table, elements)
        self.assertIsInstance(result, CayleyTable)
        self.assertEqual(result.tolist(), [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]])

    def test_from_a_table_of_names_matches_index_version(self):
        elements = ('e', 'a', 'a2', 'a3')
        index_table = [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]
        name_table = [['e', 'a', 'a2', 'a3'],
                      ['a', 'a2', 'a3', 'e'],
                      ['a2', 'a3', 'e', 'a'],
                      ['a3', 'e', 'a', 'a2']]
        self.assertEqual(make_cayley_table(index_table, elements), make_cayley_table(name_table, elements))


class TestIndexTableFromNameTable(TestCase):

    def test_basic_conversion(self):
        elements = ['r', 'p', 's']
        name_table = [['r', 'p', 'r'], ['p', 'p', 's'], ['r', 's', 's']]
        result = index_table_from_name_table(elements, name_table)
        self.assertEqual(result, [[0, 1, 0], [1, 1, 2], [0, 2, 2]])


class TestIsAssociativeLightsTest(TestCase):
    """Targeted tests for the Light's-test-based CayleyTable.is_associative."""

    def test_order_one_table_is_associative(self):
        # Exercises the n <= 1 early return.
        self.assertTrue(CayleyTable([[0]]).is_associative())

    def test_hidden_failure_past_a_trivial_generator(self):
        # Element 0 is a two-sided identity, so Light's test for g=0 passes
        # trivially no matter what the rest of the table looks like -- it can
        # never expose a non-associativity elsewhere. The real failure here is
        # at the triple (1, 1, 1): (1*1)*1 = 1 but 1*(1*1) = 2. This checks that
        # the search doesn't stop after the first (trivially-passing) generator.
        tbl = CayleyTable([[0, 1, 2],
                            [1, 2, 2],
                            [2, 1, 1]])
        self.assertFalse(tbl.is_associative())

    def test_generating_set_needs_more_than_one_element(self):
        # In V4 (Klein four-group), no single element generates the whole group
        # (every non-identity element has order 2), so this forces
        # _generating_set to pick more than one generator. Included here as a
        # belt-and-suspenders check alongside the existing V4-based table test.
        v4 = CayleyTable([[0, 1, 2, 3],
                           [1, 0, 3, 2],
                           [2, 3, 0, 1],
                           [3, 2, 1, 0]])
        self.assertTrue(v4.is_associative())

    def test_worst_case_generating_set_is_whole_table(self):
        # Right-zero semigroup: a*b = b for all a, b. It IS associative, but
        # closure({x}) = {x} for every single x, so _generating_set is forced
        # to fall back to using every element as its own generator -- the
        # worst case for Light's test. Confirms correctness (and that there's
        # no infinite loop / crash) in that worst case.
        n = 6
        rz = CayleyTable([[b for b in range(n)] for _ in range(n)])
        self.assertTrue(rz.is_associative())

    def test_closure_of_indices_matches_expected_subalgebra(self):
        # Direct test of the helper: closure of {1} in the Z4 table should
        # reach every element (1 generates the cyclic group), but closure of
        # {1} in V4 should stop at {0, 1} (1 has order 2 and doesn't reach
        # 2 or 3).
        z4 = CayleyTable([[0, 1, 2, 3],
                           [1, 2, 3, 0],
                           [2, 3, 0, 1],
                           [3, 0, 1, 2]])
        self.assertEqual(sorted(z4._closure_of_indices([1]).tolist()), [0, 1, 2, 3])

        v4 = CayleyTable([[0, 1, 2, 3],
                           [1, 0, 3, 2],
                           [2, 3, 0, 1],
                           [3, 2, 1, 0]])
        self.assertEqual(sorted(v4._closure_of_indices([1]).tolist()), [0, 1])

    def test_generating_set_actually_generates_whole_table(self):
        # General sanity check across the existing suite's tables: whatever
        # _generating_set returns, its closure really is everything -- this is
        # the invariant Light's test depends on for correctness.
        for tbl in self.all_tables if hasattr(self, "all_tables") else []:
            gens = tbl._generating_set()
            closure = tbl._closure_of_indices(gens)
            self.assertEqual(sorted(closure.tolist()), list(range(tbl.order)))

    def test_matches_brute_force_on_random_tables(self):
        # Cross-check against an independent brute-force reference (not the
        # production code) across many random small tables and orders, rather
        # than relying only on a handful of hand-picked examples.
        import random
        rng = random.Random(12345)

        def brute_force_is_associative(table):
            n = len(table)
            for a in range(n):
                for b in range(n):
                    for c in range(n):
                        if table[table[a][b]][c] != table[a][table[b][c]]:
                            return False
            return True

        for order in range(1, 7):
            for _ in range(500):
                table = [[rng.randrange(order) for _ in range(order)] for _ in range(order)]
                expected = brute_force_is_associative(table)
                actual = CayleyTable(table).is_associative()
                self.assertEqual(actual, expected, msg=f"order={order} table={table}")
