# -----------------
# Group Generators
# -----------------

import itertools as it
import numpy as np
from sympy.ntheory import isprime
# from collections.abc import Callable

from finalg.abstract_matrix import AbstractMatrix
from finalg.permutation import Perm
from finalg.make_finite_algebra import make_finite_algebra
from finalg.cayley_table import index_table_from_name_table
from finalg.utilities import powerset, compress_runs
from finalg.my_math import relative_primes
from finalg.ring import Ring

def generate_cyclic_group(order: int, elem_name: str = '', name: (str | None) = None,
                          description: (str | None) = None, zfill: bool = False):
    """Generates a cyclic group with the given order. If zfill is True, then left fill element
    names with zeros."""
    if name:
        nm = name
    else:
        nm = "Z" + str(order)
    if description:
        desc = description
    else:
        desc = f"Autogenerated cyclic group of order {order}"
    if zfill:
        nfill = len(str(order - 1))  # Number of zeros to left-fill integers in element names
        elements = [elem_name + str(i).zfill(nfill) for i in range(order)]
    else:
        elements = [elem_name + str(i) for i in range(order)]
    table = [[((a + b) % order) for b in range(order)] for a in range(order)]
    return make_finite_algebra(nm, desc, elements, table)


def generate_symmetric_group(n: int, name: (str | None) =None, description: (str | None) =None,
                             alternating: bool =False, cyclic_form:bool =True):
    """Generates a symmetric or alternating group on n elements."""
    if alternating:
        txt = ["A", "alternating"]
    else:
        txt = ["S", "symmetric"]
    if name:
        nm = name
    else:
        nm = txt[0] + str(n)
    if description:
        desc = description
    else:
        desc = f"Autogenerated {txt[1]} Group on {n} elements"
    ident = tuple(range(n))
    mappings = list(it.permutations(ident))
    perms = map(lambda x: Perm(x), mappings)
    if cyclic_form:
        if alternating:
            elem_dict = {str(p): p for p in perms if p.is_even}
        else:
            elem_dict = {str(p): p for p in perms}
    else:
        if alternating:
            elem_dict = {str(p.values): p for p in perms if p.is_even}
        else:
            elem_dict = {str(p.values): p for p in perms}
    rev_elem_dict = {val: key for key, val in elem_dict.items()}
    mul_tbl = [[rev_elem_dict[elem_dict[a] * elem_dict[b]]
                for b in elem_dict]
               for a in elem_dict]
    index_table = index_table_from_name_table(list(elem_dict.keys()), mul_tbl)
    return make_finite_algebra(nm, desc, list(elem_dict.keys()), index_table)


def generate_alternating_group(n: int, name: (str | None) =None, description: (str | None) =None,
                               cyclic_form:bool =True):
    """A convenience function for generating an alternating group. Under the hood, it simply calls
    'generate_symmetric_group' with alternating=True."""
    return generate_symmetric_group(n, name, description, alternating=True, cyclic_form=cyclic_form)


def generate_powerset_group(n: int, name: (str | None) =None, description: (str | None) =None):
    """Generates a group on the powerset of {0, 1, 2, ..., n-1},
    where symmetric difference is the operator.
    """
    if name:
        nm = name
    else:
        nm = "PS" + str(n)
    if description:
        desc = description
    else:
        desc = f"Autogenerated group on the powerset of {n} elements, with symmetric difference operator"
    set_of_n = set(list(range(n)))
    pset = [set(x) for x in list(powerset(set_of_n))]
    table = [[pset.index(a ^ b) for b in pset] for a in pset]
    elements = [str(elem) for elem in pset]
    elements[0] = "{}"  # Because otherwise it would be "set()"
    return make_finite_algebra(nm, desc, elements, table)


def generate_commutative_monoid(order: int, elem_name: str ='a', name: (str | None) =None,
                                description: (str | None) =None):
    """Generates a commutative monoid over {0,1,2,...,n-1}, where op(a,b) = (a * b) % n."""
    if name:
        nm = name
    else:
        nm = "M" + str(order)
    if description:
        desc = description
    else:
        desc = f"Autogenerated commutative monoid of order {order}"
    nfill = len(str(order - 1))  # Number of zeros to left-fill integers in element names
    elements = [elem_name + str(i).zfill(nfill) for i in range(order)]
    table = [[(a * b) % order for b in range(order)] for a in range(order)]
    return make_finite_algebra(nm, desc, elements, table)


def generate_relative_primes_group(n: int, name: (str | None) =None, description: (str | None) =None):
    """Generates a group based on mult mod n of relatively-prime numbers < n.
    In keeping with the convention in this module, the elements are converted to strings."""
    if name:
        nm = name
    else:
        nm = "RelPrimes<" + str(n)
    if description:
        desc = description
    else:
        desc = f"Autogenerated group based on relative primes < {n}"
    elems = relative_primes(n)
    elem_dict = dict(zip(elems, range(len(elems))))  # rel_prime : index_in_elem_list
    table = [[elem_dict[(a * b) % n] for b in elems] for a in elems]
    elems_as_str = [str(elem) for elem in elems]
    return make_finite_algebra(nm, desc, elems_as_str, table)


def generate_powerset_ring(n: int, name: (str | None) = None, description: (str | None) = None):
    """Generates a ring on the powerset of {0, 1, 2, ..., n-1}, where n is a positive integer,
    symmetric difference is the addition operator, and intersection is the multiplication operator."""
    if name:
        nm = name
    else:
        nm = "PSRing" + str(n)
    if description:
        desc = description
    else:
        if n < 1:
            raise ValueError(f"n = {n} is invalid; n must be a positive integer")
        elif n == 1:
            desc = f"Autogenerated Ring on powerset of {{0}} w/ symm. diff. (add) & intersection (mult)"
        elif n == 2:
            desc = f"Autogenerated Ring on powerset of {{0, 1}} w/ symm. diff. (add) & intersection (mult)"
        elif n == 3:
            desc = f"Autogenerated Ring on powerset of {{0, 1, 2}} w/ symm. diff. (add) & intersection (mult)"
        else:
            desc = f"Autogenerated Ring on powerset of {{0,...,{n-1}}} w/ symm. diff. (add) & intersection (mult)"
    set_of_n = set(list(range(n)))
    pset = [set(x) for x in list(powerset(set_of_n))]
    addition_table = [[pset.index(a ^ b) for b in pset] for a in pset]
    mult_table = [[pset.index(a & b) for b in pset] for a in pset]
    elements = [str(elem) for elem in pset]
    elements[0] = '{}'  # Because 'set()' doesn't look cool
    return make_finite_algebra(nm, desc, elements, addition_table, mult_table)


def generate_algebra_mod_n(n: int, elem_name: str ='', name: (str | None) =None,
                           description: (str | None) =None):
    """Generate a ring (or field) based on integer addition and multiplication modulo n.
    If n is prime, then result will be a Field, otherwise it will be a Ring."""

    if isprime(n):
        prime = True
    else:
        prime = False

    if name:
        nm = name
    elif prime:
        nm = "F" + str(n)
    else:
        nm = "R" + str(n)

    if description:
        desc = description
    elif prime:
        desc = f"Autogenerated field of integers mod {n}"
    else:
        desc = f"Autogenerated ring of integers mod {n}"

    nfill = len(str(n - 1))  # Number of zeros to left-fill integers in element names
    elements = [elem_name + str(i).zfill(nfill) for i in range(n)]
    add_table = [[(a + b) % n for b in range(n)] for a in range(n)]
    mult_table = [[(a * b) % n for b in range(n)] for a in range(n)]
    return make_finite_algebra(nm, desc, elements, add_table, mult_table)


def generate_nxn_matrix_algebra(ring: Ring, element_name_prefix: str ='a'):
    """Generate a ring (or field) based on all possible 2x2 abstract matrices using
    elements from the input ring. For now, n is hardcoded to 2.
    Three items are returned:
    (1) the generated ring,
    (2) a dictionary of element names (keys) to matrices (values), and
    (3) a reverse dictionary of matrices (as tuples of tuples) to element names.
    """
    n = 2  # Square matrix dimension. Hardcoded to 2 for now.

    # Create all possible matrices, and give them names.
    # Then create a dictionary that maps each name (key) to its matrix (value).
    # Also, create a reverse dictionary of matrices (as tuples) mapped to names.
    count = 0
    elem_dict = dict()
    rev_dict = dict()
    elements = ring.elements
    for e00 in elements:  # TODO: Replace these for-loops so that n can be >= 2
        for e01 in elements:
            for e10 in elements:
                for e11 in elements:
                    mat = AbstractMatrix([[e00, e01], [e10, e11]], ring)
                    elem_name = element_name_prefix + str(count)
                    elem_dict[elem_name] = mat
                    rev_dict[mat.to_tuple()] = elem_name
                    count += 1

    # Create the Cayley table for addition of the matrix elements
    m = len(elem_dict)
    add_table = np.empty((m, m), AbstractMatrix)
    for row, elemr in enumerate(elem_dict.keys()):
        for col, elemc in enumerate(elem_dict.keys()):
            result = elem_dict[elemr] + elem_dict[elemc]
            name = rev_dict[result.to_tuple()]
            add_table[row][col] = name

    # Create the Cayley table for multiplication of the matrix elements
    mul_table = np.empty((m, m), AbstractMatrix)
    for row, elemr in enumerate(elem_dict.keys()):
        for col, elemc in enumerate(elem_dict.keys()):
            result = elem_dict[elemr] * elem_dict[elemc]
            name = rev_dict[result.to_tuple()]
            mul_table[row][col] = name

    name = f"{ring.name}_{n}x{n}"
    description = f"Algebra of {n}x{n} abstract matrices based on {ring.name}"
    elements = list(elem_dict.keys())
    algebra = make_finite_algebra(name, description, elements, add_table, mul_table)

    return algebra, elem_dict, rev_dict


def generate_dihedral_group(n: int, verbose: bool =False):
    """Automatically generate a dihedral group of order 2n."""

    r = Perm.from_cycles([list(range(0, n))])  # Rotation

    # Flip: fixes 0 and swaps vertex k with vertex n-k for k = 1,...,n-1
    f_list = list(range(1, n))
    f_list.reverse()
    f = Perm([0] + f_list)

    if verbose:
        print(f"\nGenerating the dihedral group D{2 * n} from the following two permutations, in cycle form:")
        print(f"  Rotate: r = {r}")
        print(f"    Flip: f = {f}")

    # Identity permutation (not required, but gives it a recognizable name)
    e = Perm.identity(n)

    # Generator elements
    gens = {'e': e, 'r': r, 'f': f}

    # Create the first version of the group
    alg, elem_dict, iterations = generate_algebra_from_element_dict(
        gens,
        name=f"D{2 * n}",
        description=f"Autogenerated dihedral group of order {2 * n}"
    )
    # Create the second version of the group.
    # The purpose here is to compress character runs in element names,
    # and the easiest way to do that is to create a new version of the
    # group by cannibalizing the previous version.
    new_elem_dict = {compress_runs(key): val for key, val in elem_dict.items()}
    new_elems = list(new_elem_dict.keys())
    new_alg = make_finite_algebra(alg.name, alg.description, new_elems, alg.table.table)
    return new_alg, new_elem_dict, iterations


def generate_algebra_from_element_dict(gen_elem_dict,
                                       bin_op=lambda x, y: x * y,
                                       elem_eq=lambda x, y: x == y,
                                       make_immutable=lambda x: x,
                                       make_elem_key=lambda key1, key2, _: key1 + key2,
                                       name="Generated Algebra",
                                       description="Created from a set of generators",
                                       closed=False,
                                       max_iter=100):
    """Return an algebra, an element mapping, and iteration counter, given...

    (1) gen_elem_dict: a dictionary of generator elements, where the keys
    are unique string names of the elements, and the values are the actual element
    objects (e.g., numbers, matrices, sets, etc.),

    (2) bin_op: a binary operation that combines two element values into a new value.
    The default value assumes that multiplication is defined for the elements.

    (3) elem_eq: a binary operation that returns True if the two element values are equal.
    The default value assumes that equality is defined for the elements.

    (4) make_immutable: a function that takes an element value and returns a unique immutable
        object that can be used as a dictionary key. This is used to create a reverse dictionary
        that maps values to keys. The default value is the identity function, which assumes
        that the elements are already immutable.

    (5) make_elem_name: a function of three arguments, where the first two arguments
        are assumed to be element keys (str), and the third is assumed to be an element
        value that is the product of the element values corresponding to the two keys.
        The function must return a string that can be used as a key for the product.
        The default value ignores the third argument (product) and simply concatenates
        the two element keys to produce the name (key) of their product. The third argument,
        product, is included because there might be instances where the key can be generated
        by simply turning the product into a string.

    If closed is False, then this function uses bin_op to compute the closure by combining
    the input elements, and combinations of them, with each other, repeatedly, until no new
    elements are generated, assuming this happens before the max_iter number of iterations
    is obtained.

    The element mapping that is returned is the (possibly) expanded set of elements generated
    from the initial input, gen_elem_dict.

    The counter value returned is a positive integer that represents the number of
    iterations required to compute the fully closed set of elements. If the input
    dictionary represents a closed set of elements, the counter value will always
    be 1.
    """
    counter = 1
    elem_dict = dict(gen_elem_dict)  # shallow copy of input dict

    # If necessary, expand the input dictionary of generators to its closure.
    if not closed:
        while counter < max_iter:
            new_dict = dict()
            elem_values = elem_dict.values()
            for key1 in elem_dict:
                for key2 in elem_dict:
                    prod = bin_op(elem_dict[key1], elem_dict[key2])
                    if not (any([elem_eq(prod, arr) for arr in elem_values]) or
                            any([elem_eq(prod, arr) for arr in new_dict.values()])):
                        prod_key = make_elem_key(key1, key2, prod)
                        new_dict[prod_key] = prod
            if not new_dict:
                break
            else:
                counter += 1
                elem_dict = dict(list(elem_dict.items()) + list(new_dict.items()))
        else:
            print(f"WARNING: Maximum number of iterations reached: {max_iter}")
            print("         The resulting algebra might be incomplete.")
            print("         Try increasing max_iter.")

    # Derive a reverse element dictionary
    rev_elem_dict = {make_immutable(val): key for key, val in elem_dict.items()}

    # Extract the list of element names
    elements = list(elem_dict.keys())

    # Derive the multiplication table
    table = [[elements.index(rev_elem_dict[make_immutable(bin_op(elem_dict[a], elem_dict[b]))])
              for b in elem_dict]
             for a in elem_dict]

    # Derive the algebra generated by the input elements
    return (make_finite_algebra(name, description, elements, table),
            elem_dict,
            counter)



